plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.165'
}

version = '1.21.1-1.20.0'
group = 'hellfirepvp.astralsorcery'
archivesBaseName = 'astralsorcery'

ext.mod_id = 'astralsorcery'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

repositories {
    mavenLocal()
    maven { url 'https://maven.hellfiredev.net/' }
    maven { url 'https://maven.theillusivec4.top/' }
    maven { url 'https://dvs1.progwml6.com/files/maven' }
    maven { url 'https://maven.blamejared.com' }
    maven {
        url 'https://www.cursemaven.com'
        content { includeGroup 'curse.maven' }
    }
    maven { url 'https://maven.neoforged.net/releases' }
    mavenCentral()
}

dependencies {
    compileOnly files('libs/observerlib-1.10.1.21.jar')
    runtimeOnly files('libs/observerlib-1.10.1.21.jar')
    compileOnly 'org.spongepowered:mixin:0.8.5'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly 'net.neoforged:neoforge:21.1.18'
    implementation 'top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1'
    runtimeOnly 'top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1'
    compileOnly 'mezz.jei:jei-1.21.1-common-api:19.27.0.340'
    compileOnly 'mezz.jei:jei-1.21.1-neoforge-api:19.27.0.340'
    runtimeOnly 'mezz.jei:jei-1.21.1-neoforge:19.27.0.340'
    compileOnly 'vazkii.patchouli:Patchouli:1.21.1-93-NEOFORGE:api'
    runtimeOnly 'vazkii.patchouli:Patchouli:1.21.1-93-NEOFORGE'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

jar {
    manifest {
        attributes([
            'Specification-Title': 'astralsorcery',
            'Specification-Vendor': 'hellfirepvp',
            'Implementation-Title': project.name,
            'Implementation-Version': version,
            'Implementation-Vendor': 'hellfirepvp',
            'MixinConnector': 'hellfirepvp.astralsorcery.MixinConnector'
        ])
    }
}
