plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.165'
}

version = '1.21.1-1.20.0'
group = 'hellfirepvp.astralsorcery'
archivesBaseName = 'astralsorcery'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        superTypes.clear()
        modSource project.sourceSets.main
        workingDirectory project.file('run')
        
        systemProperty 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
        systemProperty 'forge.logging.console.level', 'info'
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenLocal()
    maven {
        name 'hellfirepvp maven'
        url 'https://maven.hellfiredev.net/'
    }
    maven {
        name 'curios maven'
        url "https://maven.theillusivec4.top/"
    }
    maven {
        name 'JEI maven'
        url "https://dvs1.progwml6.com/files/maven"
    }
    maven {
        name 'Botania maven'
        url "https://maven.blamejared.com"
    }
    maven {
        name 'CF maven'
        url "https://www.cursemaven.com"
    }
}

dependencies {
    implementation 'net.neoforged:neoforge:21.1.74'
    
    // ObserverLib - потребуется обновить версию для 1.21.1
    compileOnly 'hellfirepvp.observerlib:observerlib:1.21.1-2.0.0'
    runtimeOnly 'hellfirepvp.observerlib:observerlib:1.21.1-2.0.0'
    
    // Curios для NeoForge
    compileOnly "top.theillusivec4.curios:curios-neoforge-1.21.1:14.0.0-beta.1:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge-1.21.1:14.0.0-beta.1"
    
    // JEI
    compileOnly "mezz.jei:jei-1.21.1-common-api:19.21.0.247"
    compileOnly "mezz.jei:jei-1.21.1-neoforge-api:19.21.0.247"
    runtimeOnly "mezz.jei:jei-1.21.1-neoforge:19.21.0.247"
    
    // Patchouli
    compileOnly "vazkii.patchouli:Patchouli:1.21-87-NEOFORGE:api"
    runtimeOnly "vazkii.patchouli:Patchouli:1.21-87-NEOFORGE"
    
    // Botania
    compileOnly "vazkii.botania:Botania:1.21-458-NEOFORGE:api"
    runtimeOnly "vazkii.botania:Botania:1.21-458-NEOFORGE"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

jar {
    manifest {
        attributes([
            "Specification-Title": "astralsorcery",
            "Specification-Vendor": "hellfirepvp",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": version,
            "Implementation-Vendor": "hellfirepvp",
            "MixinConnector": "hellfirepvp.astralsorcery.MixinConnector"
        ])
    }
}

java {
    withSourcesJar()
}
